spring:
  datasource:
    #jayspt  DB ?? ??? ??.
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/springdata
    username: root
    password: 1q2w3e4r!@#
  jpa:
    hibernate:
      ddl-auto: create